### ISSUE TITLE
Can't open service port 443 with traefik

### ISSUE THREAD

**Issue by jingslunt** [rancher/server-chart#21]
I use traefik-ingress.
The command `kubectl get svc -o wide -n cattle-system`  show port is 80,not 443
Can't open url https://rancher.192.168.1.234.xip.io/ .How can i do that
* rancher-ing.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rancher-ingress
  namespace: cattle-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: rancher.192.168.1.234.xip.io
    http:
      paths:
      - backend:
          serviceName: rancher
          servicePort: 80
```
